'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

const sizingProperties = {
  minW: "min-width",
  maxW: "max-width",
  minWidth: "min-width",
  maxWidth: "max-width",
  w: "width",
  width: "width",
  h: "height",
  height: "height",
  minH: "min-height",
  minHeight: "min-height",
  maxH: "max-height",
  maxHeight: "max-height"
};
const listingProperties = {
  listStyleType: "list-style-type",
  listStyle: "list-style"
};
const borderProperties = {
  border: "border",
  borderW: "border-width",
  borderWidth: "border-width",
  borderRadius: "border-radius",
  borderTopLeftRadius: "border-top-left-radius",
  borderTopRightRadius: "border-top-right-radius",
  borderBottomLeftRadius: "border-bottom-left-radius",
  borderBottomRightRadius: "border-bottom-right-radius",
  borderTop: "border-top",
  borderBottom: "border-bottom",
  borderRight: "border-right",
  borderLeft: "border-left",
  borderStyle: "border-style",
  borderColor: "border-color",
  borderBlock: "border-block",
  borderBlockColor: "border-block-color",
  borderBlockStyle: "border-block-style",
  borderBlockWidth: "border-block-width",
  borderBlockEnd: "border-block-end",
  borderBlockStart: "border-block-start",
  borderInline: "border-inline",
  borderInlineColor: "border-inline-color",
  borderInlineStyle: "border-inline-style",
  borderInlineWidth: "border-inline-width",
  borderInlineEnd: "border-inline-end",
  borderInlineStart: "border-inline-start",
  borderTopColor: "border-top-color",
  borderTopStyle: "border-top-style",
  borderTopWidth: "border-top-width",
  borderBottomColor: "border-bottom-color",
  borderBottomStyle: "border-bottom-style",
  borderBottomWidth: "border-bottom-width",
  borderLeftColor: "border-left-color",
  borderLeftStyle: "border-left-style",
  borderLeftWidth: "border-left-width",
  borderRightColor: "border-right-color",
  borderRightStyle: "border-right-style",
  borderRightWidth: "border-right-width"
};
const pxProperties = {
  p: "padding",
  pt: "padding-top",
  pr: "padding-right",
  pb: "padding-bottom",
  pl: "padding-left",
  m: "margin",
  mt: "margin-top",
  mr: "margin-right",
  mb: "margin-bottom",
  ml: "margin-left",
  padding: "padding",
  paddingTop: "padding-top",
  paddingRight: "padding-right",
  paddingBottom: "padding-bottom",
  paddingLeft: "padding-left",
  margin: "margin",
  marginTop: "margin-top",
  marginRight: "margin-right",
  marginBottom: "margin-bottom",
  marginLeft: "margin-left",
  marginInline: "margin-inline",
  ...sizingProperties,
  ...borderProperties,
  ...listingProperties,
  top: "top",
  bottom: "bottom",
  right: "right",
  left: "left",
  letterSpacing: "letter-spacing",
  fontSize: "font-size",
  fontFamily: "font-family",
  lineHeight: "line-height",
  gap: "gap",
  rowGap: "row-gap",
  columnGap: "column-gap"
};
const nonPxProperties = {
  shadow: "box-shadow",
  boxShadow: "box-shadow",
  opacity: "opacity",
  cursor: "cursor",
  objectFit: "object-fit",
  outline: "outline",
  pointerEvents: "pointer-events",
  userSelect: "user-select",
  translate: "translate",
  transformOrigin: "transform-origin",
  transitionProperty: "transition-property",
  transitionDuration: "transition-duration",
  transitionFunction: "transition-function",
  transitionDelay: "transition-delay",
  borderStyle: "border-style",
  borderColor: "border-color",
  bgImage: "background-image",
  backgroundImage: "background-image",
  bgColor: "background-color",
  backgroundColor: "background-color",
  bgRepeat: "background-repeat",
  bgSize: "background-size",
  bgPosition: "background-position",
  display: "display",
  overflow: "overflow",
  position: "position",
  zIndex: "z-index",
  transition: "transition",
  animation: "animation",
  animationDuration: "animation-duration",
  animationDelay: "animation-delay",
  animationFunction: "animation-function",
  animationFill: "animation-fill-mode",
  justifyContent: "justify-content",
  alignContent: "align-content",
  alignItems: "align-items",
  alignSelf: "align-self",
  verticalAlign: "vertical-align",
  aspectRatio: "aspect-ratio",
  flex: "flex",
  flexBasis: "flex-basis",
  flexDirection: "flex-direction",
  flexWrap: "flex-wrap",
  flexGrow: "flex-grow",
  flexShrink: "flex-shrink",
  flexOrder: "order",
  fontWeight: "font-weight",
  fontColor: "color",
  color: "color",
  fontStyle: "font-style",
  textAlign: "text-align",
  textDecoration: "text-decoration",
  textOverflow: "text-overflow",
  textTransform: "text-transform",
  lineHeight: "line-height",
  whiteSpace: "white-space",
  templateAreas: "grid-template-areas",
  gridTemplateRows: "grid-template-rows",
  gridTemplateColumns: "grid-template-columns",
  templateColumns: "grid-template-columns",
  templateRows: "grid-template-rows",
  autoFlow: "grid-auto-flow",
  autoRows: "grid-auto-rows",
  autoColumns: "grid-auto-columns",
  area: "grid-area",
  rowStart: "grid-row-start",
  rowEnd: "grid-row-end",
  colStart: "grid-column-start",
  colEnd: "grid-column-end",
  colSpan: "grid-column",
  rowSpan: "grid-row"
};
const propertiesWithoutCssEquivalent = {
  px: null,
  py: null,
  mx: null,
  my: null,
  paddingHorizontal: null,
  paddingVertical: null,
  marginHorizontal: null,
  marginVertical: null,
  appearance: null,
  rotate: null,
  columns: null,
  rows: null,
  borderRadiusTop: null,
  borderRadiusBottom: null,
  borderRadiusRight: null,
  borderRadiusLeft: null,
  _hover: null,
  _focus: null,
  _focusVisible: null,
  _active: null,
  _disabled: null,
  _visited: null,
  _checked: null,
  _placeholder: null,
  _selection: null,
  _firstChild: null,
  _lastChild: null,
  borderX: null,
  borderY: null,
  translateX: null,
  translateY: null,
  animationIteration: null,
  colOffset: null
  // CSS does not have an equivalent for this
};
var mapCssProperties = {
  ...pxProperties,
  ...nonPxProperties,
  ...propertiesWithoutCssEquivalent
};

exports.borderProperties = borderProperties;
exports.default = mapCssProperties;
exports.listingProperties = listingProperties;
exports.nonPxProperties = nonPxProperties;
exports.propertiesWithoutCssEquivalent = propertiesWithoutCssEquivalent;
exports.pxProperties = pxProperties;
exports.sizingProperties = sizingProperties;
//# sourceMappingURL=index.web.cjs.map
