export default {
    //Buttons
    continue: 'Continue',
    submit: 'Submit',
    cancel: 'Cancel',
    add: 'Add',
    update: 'Update',
    close: 'Close',
    disable:'Disable',
    edit:'Edit',
    delete:'Delete',
    ok: 'Ok',
    done: 'Done',
    change: 'Change',
    pleaseSelect: 'Please Select',
    saveChanges: 'Save Changes',
    showAll: 'See All',
    resendCode: 'Resend Code!',
    register: 'Sign Up',
    signUp: 'Register',
    addToCart: 'Add to cart',
    updateCart: 'Update cart',
    home: 'Home',
    ordersList: 'My Orders',
    whoWeAre: 'About Us',
    settings: 'Settings',
    logOut: 'Logout',
    deleteUser: 'Delete Account',
    viewMore: 'See More',
    viewLess: 'See Less',
    addNewAddress: 'Add New Address',
    backToMap: 'Back to Map',
    login: 'Sign In',
    continueAsGuest: 'Continue As Guest',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    send: 'Send',
    addAdmin: 'Add new admin',
    addAuthor: 'Add new author',
};
