export default {
    eventDetails:'Event Details',
    mainDetails:'Main Details',
    actions:'Actions',
    repeatConfiguration:'Repeat Configuration',
    or:'OR',
    eventTypeName:'Event Type Name',
    displayOptions:'Display Options',
    lineColor:'Line Color',
    timing:'Timing',
    styling:'Styling',
    arabic:'Arabic',
    english:'English',
    details:'Details',
    videoSource:'Video Source',
    videoDetails:'Video Details',
    postTitle:'Post Title',
    bible:'Bible',
    saintName:'Saint Name',
}
