export default {
    aiMessage: "للأحداث العامة ، يرجى تقديم العنوان الكامل. يمكننا ملء الحقول المتبقية تلقائياً للأحداث المعروفة.",
    hourly: 'كل ساعة',
    daily: 'يوميا',
    weekly: 'أسبوعيا',
    fortnightly: 'كل أسبوعين',
    monthly: 'شهريا',
    quarterly: 'ربع سنوي',
    biannually: 'مرتين في السنة',
    annually: 'سنويا',
    day:'يوم',
    month:'شهر',
    year:'سنة',
    list:'قائمة',
    today:'اليوم',
    noEvents:'لا يوجد معلومات لعرض',
    repeated: 'متكرر',
    notRepeated: 'غير متكرر',
    repeatEvery: 'كرر كل',
    repeatUntil: 'كرر حتى',
    allDay: 'طوال اليوم',
    atChurch:'في الكنيسة',
    editCalenderItem:'تحرير عنصر التقويم',
    addCalenderItem:'إضافة عنصر التقويم',
    eventTitle:'عنوان الحدث',
    startDate:'تاريخ البدء',
    endDate:'تاريخ الانتهاء',
    startTime:'وقت البدء',
    endTime:'وقت الانتهاء',
    preview:'معاينة',

};
