export default {
    searchQuery: 'استعلام البحث',
    enterSearchQuery: 'أدخل استعلام البحث',
    channelOperator: 'اسم القناة (القناة: عامل التشغيل)',
    channelName: 'اسم القناة',
    playlist: 'قائمة التشغيل (قائمة التشغيل: عامل التشغيل)',
    playlistName: 'اسم قائمة التشغيل',
    hashtagOperator: 'الوسم (#الوسم: عامل التشغيل)',
    hashtag: 'الوسم',
    afterDateOperator: 'بعد (بعد: عامل التاريخ)',
    beforeDateOperator: 'قبل (قبل: عامل التاريخ)',
    selectDate: 'اختر التاريخ',
    exactMatch: 'مطابقة تامة ("عبارة دقيقة" عامل التشغيل)',
    exactPhrase: 'عبارة دقيقة',
    exclude: 'استبعاد (-استبعاد: عامل التشغيل)',
    excludeTerm: 'استبعاد المصطلح',
    titleSearchOperator: 'البحث في العنوان (في العنوان: عامل التشغيل)',
    titleTerm:'مصطلح العنوان',
    titleSearch: 'البحث في العنوان',
    searchYoutube: 'بحث في يوتيوب',
};
