export default {
    aiMessage: 'For public events, please provide the full title. We can auto-fill the remaining fields for well-known events.',
    hourly: 'Hourly',
    daily: 'Daily',
    weekly: 'Weekly',
    fortnightly: 'Fortnightly',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    biannually: 'Biannually',
    annually: 'Annually',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    list: 'List',
    today: 'Today',
    noEvents: 'No Events available to display',
    repeated: 'Repeated',
    notRepeated: 'Not Repeated',
    repeatEvery: 'Repeat Every',
    repeatUntil: 'Repeat Until',
    allDay: 'All Day',
    atChurch:'At Church',
    editCalenderItem:'Edit Calender Item',
    addCalenderItem:'Add Calender Item',
    eventTitle:'Event Title',
    startDate:'Start date',
    endDate:'End date',
    startTime:'Start Time',
    endTime:'End Time',
    preview:'Preview',
};
