export default {
    searchQuery:'Search Query',
    enterSearchQuery:'Enter Search Query',
    channelOperator:'Channel Name (channel: operator)',
    channelName:'Channel Name',
    playlist:'Playlist (playlist: operator)',
    playlistName :'Playlist Name',
    hashtagOperator:'Hashtag (#hashtag operator)',
    hashtag:'Hashtag',
    afterDateOperator:'After (after: date operator)',
    beforeDateOperator:'Before (before: date operator)',
    selectDate:'Select Date',
    exactMatch:'Exact Match ("exact phrase" operator)',
    exactPhrase:'Exact Phrase',
    exclude:'Exclude (-exclude operator)',
    excludeTerm:'Exclude Term',
    titleSearchOperator:'Title Search (in title: operator)',
    titleTerm:'Title term',
    titleSearch:'Title Search',
    searchYoutube:'Search Youtube',
}