import 'react-icons/fa';
import 'react-icons/ai';
import 'react-icons/io';
import '../../../../../packages/types/src/Components/Molecules/Form/FilePicker/types/filesTypes.js';
import 'yup';
import { isThemeToken } from '../../../../../packages/types/src/Theme/resolvers.js';

const CSS_COLOR_NAMES = /* @__PURE__ */ new Set([
  "aqua",
  "black",
  "blue",
  "fuchsia",
  "gray",
  "green",
  "lime",
  "maroon",
  "navy",
  "olive",
  "purple",
  "red",
  "silver",
  "teal",
  "white",
  "yellow",
  "aliceblue",
  "antiquewhite",
  "aquamarine",
  "azure",
  "beige",
  "bisque",
  "blanchedalmond",
  "blueviolet",
  "brown",
  "burlywood",
  "cadetblue",
  "chartreuse",
  "chocolate",
  "coral",
  "cornflowerblue",
  "cornsilk",
  "crimson",
  "cyan",
  "darkblue",
  "darkcyan",
  "darkgoldenrod",
  "darkgray",
  "darkgreen",
  "darkgrey",
  "darkkhaki",
  "darkmagenta",
  "darkolivegreen",
  "darkorange",
  "darkorchid",
  "darkred",
  "darksalmon",
  "darkseagreen",
  "darkslateblue",
  "darkslategray",
  "darkslategrey",
  "darkturquoise",
  "darkviolet",
  "deeppink",
  "deepskyblue",
  "dimgray",
  "dimgrey",
  "dodgerblue",
  "firebrick",
  "floralwhite",
  "forestgreen",
  "gainsboro",
  "ghostwhite",
  "gold",
  "goldenrod",
  "greenyellow",
  "grey",
  "honeydew",
  "hotpink",
  "indianred",
  "indigo",
  "ivory",
  "khaki",
  "lavender",
  "lavenderblush",
  "lawngreen",
  "lemonchiffon",
  "lightblue",
  "lightcoral",
  "lightcyan",
  "lightgoldenrodyellow",
  "lightgray",
  "lightgreen",
  "lightgrey",
  "lightpink",
  "lightsalmon",
  "lightseagreen",
  "lightskyblue",
  "lightslategray",
  "lightslategrey",
  "lightsteelblue",
  "lightyellow",
  "limegreen",
  "linen",
  "magenta",
  "mediumaquamarine",
  "mediumblue",
  "mediumorchid",
  "mediumpurple",
  "mediumseagreen",
  "mediumslateblue",
  "mediumspringgreen",
  "mediumturquoise",
  "mediumvioletred",
  "midnightblue",
  "mintcream",
  "mistyrose",
  "moccasin",
  "navajowhite",
  "oldlace",
  "olivedrab",
  "orange",
  "orangered",
  "orchid",
  "palegoldenrod",
  "palegreen",
  "paleturquoise",
  "palevioletred",
  "papayawhip",
  "peachpuff",
  "peru",
  "pink",
  "plum",
  "powderblue",
  "rosybrown",
  "royalblue",
  "saddlebrown",
  "salmon",
  "sandybrown",
  "seagreen",
  "seashell",
  "sienna",
  "skyblue",
  "slateblue",
  "slategray",
  "slategrey",
  "snow",
  "springgreen",
  "steelblue",
  "tan",
  "thistle",
  "tomato",
  "turquoise",
  "violet",
  "wheat",
  "whitesmoke",
  "yellowgreen"
]);
const VALUE_PATTERNS = [
  /^[-+]?\d*\.?\d+(px|em|rem|vh|vw|cm|mm|Q|in|pt|pc|ex|ch|lh|vmin|vmax|%)$/i,
  /^[-+]?\d*\.?\d+%$/,
  /^url\(['"]?(.*?)['"]?\)$/,
  /^[-+]?\d*\.?\d+(deg|grad|rad|turn)$/,
  /^[-+]?\d*\.?\d+(s|ms)$/,
  /^(inherit|initial|unset)$/,
  /^var\(--\S+\)$/,
  /^(left|right|center|justify|start|end)$/,
  /^(baseline|sub|super|top|text-top|middle|bottom|text-bottom)$/,
  /^(flex-start|flex-end|center|space-between|space-around|space-evenly)$/,
  /^(flex-start|flex-end|center|baseline|stretch)$/,
  /^(start|end|center|stretch)$/,
  /^(left|right|none)$/,
  /^(row|column|column-reverse|row-reverse)$/,
  /^(cover|contain|stretch)$/,
  /^(static|relative|fixed|absolute|sticky)$/,
  /^(block|flex|grid)$/,
  /^[-+]?\d+$/,
  /^auto$/,
  /^span \d+$/,
  /!important$/,
  /^#([0-9a-f]{3}|[0-9a-f]{6})$/i,
  /^rgb\(\s?(\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3})\s?\)$/i,
  /^.*\(.+\).*$/,
  /^[-+]?\d*\.?\d+(px|em|rem|vh|vw|cm|mm|Q|in|pt|pc|ex|ch|lh|vmin|vmax|%)\s(solid|dashed|dotted|double|groove|ridge|inset|outset|none|hidden)?\s?(#[0-9a-fA-F]{3}(?:[0-9a-fA-F]{3})?|rgba?\((-?\d+%?[,\s]+){2,3}\s*[\d\.]+%?\)|black|white|blue|green|red|yellow|purple|cyan|aqua|lime|maroon|navy|olive|silver|teal|gray|grey|fuchsia|)?$/i
];
const SIZING_KEYS = ["width", "height", "min-width", "max-width", "min-height", "max-height"];
const isCssValue = (value, key) => {
  if (typeof value === "string" && isThemeToken(value)) return true;
  if (typeof value === "string" && value.includes("!important")) {
    if (CSS.supports(key, value.replace("!important", ""))) return true;
  } else {
    if (CSS.supports(key, value)) return true;
  }
  if (key === "col-offset") return false;
  if ((value === "full" || value === "screen") && SIZING_KEYS.includes(key)) {
    return true;
  }
  if (CSS_COLOR_NAMES.has(value)) return true;
  for (const pattern of VALUE_PATTERNS) {
    if (pattern.test(value)) return true;
  }
  return false;
};

export { isCssValue };
//# sourceMappingURL=validate.js.map
