export default {
    //Buttons
    continue: 'استمر',
    submit: 'تم',
    cancel: 'إلغاء',
    update: 'تحديث',
    add: 'إضافة',
    close: 'إغلاق',
    disable:'تعطيل',
    edit:'تعديل',
    delete:'حذف',
    ok: 'نعم',
    done: 'تم',
    change: 'تعديل',
    pleaseSelect: 'يرجى التحديد',
    saveChanges: 'حفظ',
    showAll: 'مشاهدة الكل',
    resendCode: 'أعد إرسال الرمز',
    register: 'التسجيل',
    signUp: 'التسجيل',
    addToCart: 'أضف الى السلة',
    updateCart: 'عدل السلة',
    home: 'الرئيسية',
    ordersList: 'طلباتي',
    whoWeAre: 'من نحن',
    settings: 'الضبط',
    logOut: 'تسجيل الخروج',
    deleteUser: 'مسح الحساب',
    viewMore: 'قراءة المزيد',
    viewLess: 'تراجع',
    addNewAddress: 'إضافة عنوان جديد',
    backToMap: 'الرجوع إلى الخريطة',
    login: 'تسجيل الدخول',
    continueAsGuest: 'استمر كزائر',
    confirm: 'تأكيد',
    yes: 'نعم',
    no: 'لا',
    send: 'إرسال',
    addAdmin: 'إضافة مدير جديد',
    addAuthor: 'إضافة مؤلف جديد',

};
