export default {
    eventDetails:'تفاصيل الحدث',
    mainDetails:'التفاصيل الرئيسية',
    actions:'الإجراءات',
    repeatConfiguration:"إعدادات التكرار",
    or:'أو',
    eventTypeName:'اسم نوع الحدث',
    displayOptions:'خيارات العرض',
    lineColor:'لون الخط',
    timing:'التوقيت',
    styling:'التنسيق',
    arabic: 'العربية',
    english: 'الإنجليزية',
    details: 'التفاصيل',
    videoSource: 'مصدر الفيديو',
    videoDetails: 'تفاصيل الفيديو',
    postTitle: 'عنوان المنشور',
    bible: 'الكتاب المقدس',
    saintName: 'اسم القديس',
}
